### ISSUE TITLE
TypeError: this.customTesters is not iterable in expect.jsonContaining in jest 29.4.0

### ISSUE THREAD

**Issue by justin-tay** [debugmaster/jest-json-matchers#9]
After upgrading jest to 29.4.0. Using `expect.jsonContaining` triggers the following error `TypeError: this.customTesters is not iterable`.

I suspect this is likely due to changes from https://github.com/facebook/jest/pull/13654.

https://github.com/debugmaster/jest-json-matchers/blob/469552f7dcbcbc78a5dbb91d8dc2cbe0ca986fa9/index.ts#L75 I think that instead of using `expect.getState()` the `this` variable is expected to be passed through.

**Comment by debugmaster** [comment]
Thanks for your report @justin-tay. I will have a look later today.
